require "tagen/core/kernel/shell"
require "tagen/core/kernel/deprecate"
require "tagen/core/kernel/platform"
require "active_support/core_ext/kernel/reporting" 
require "active_support/core_ext/kernel/agnostics"
