require "pd"

require "tagen/core/object"
require "tagen/core/kernel"
require "tagen/core/module"
require "tagen/core/class"

require "tagen/core/numeric"
require "tagen/core/integer"
require "tagen/core/string"
require "tagen/core/enumerable"
require "tagen/core/enumerator"
require "tagen/core/array"
require "tagen/core/hash"
require "tagen/core/time"
require "tagen/core/exception"
require "tagen/core/io"
require "tagen/core/process"
require "tagen/core/re"

require "active_support/concern"
require "active_support/deprecation"
